language: node_js
node_js:
  - '8'

cache:
  directories:
    - node_modules

before_install:
  - npm set progress=false
  - export CHROME_BIN=/usr/bin/google-chrome
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

install:
  - npm install
  - npm install surge

script:
  - npm run build:css
  - npm run test:all
  - npm run build

after_success:
  - npm run coverage

branches:
  only:
    - master

deploy:
  skip_cleanup: true
  provider: script
  script: npm run deploy
  on:
    branch: master
